name: "GitHub Release Notes"
description: "GitHub release notes and changelog generator using Gren"
inputs:
  options:  # Add the gren options here
    description: 'Add the gren options here; e.g. " --override --prerelease"'
    required: false
    default: '-c .grenrc.js --override'
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.options }}